services:

  db:
    image: postgres:17
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=techtask
      - POSTGRES_PASSWORD=techtask
      - POSTGRES_DB=postgres
    volumes:
      - ./dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:

    image: app:1.0.0

    build:
      context: .
      dockerfile: Dockerfile

    container_name: tomee-app
    depends_on:
      - db
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/postgres
      - DATABASE_USER=techtask
      - DATABASE_PASSWORD=techtask
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local